update github action

diff --git a/.github/workflows/script.yml b/.github/workflows/script.yml
--- a/.github/workflows/script.yml
+++ b/.github/workflows/script.yml
@@ -7,13 +7,28 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
+
       - name: Set up Python
         uses: actions/setup-python@v3
         with:
           python-version: '3.12'
+
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           pip install -r .github/workflows/requirements.txt
+
       - name: Run script
         run: python main/Solve_CW_4All.py
+
+      - name: List files in the current directory
+        run: ls -la
+
+      - name: Check if CSV file exists
+        run: |
+          if [ -f ./path/to/your_output.csv ]; then
+            echo "CSV file created successfully."
+          else
+            echo "CSV file not found."
+            exit 1
+          fi
